package models.enums;

public enum DocumentType {

  ISSUE_COVER_LETTER,
  AMENDMENT_COVER_LETTER,
  ISSUE_LICENCE_DOCUMENT,
  AMENDMENT_LICENCE_DOCUMENT,
  ISSUE_NLR_DOCUMENT,
  AMENDMENT_NLR_DOCUMENT,
  ISSUE_REFUSE_DOCUMENT,
  AMENDMENT_REFUSE_DOCUMENT,
  ISSUE_AMENDMENT_LETTER,
  AMENDMENT_AMENDMENT_LETTER

}
